
version: '3'

services:

  shard1:
    container_name: shard1
    image: mongo:4.2
    command: mongod --shardsvr --replSet shardRepl --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard1:/data/db

  shard2:
    container_name: shard2
    image: mongo:4.2
    command: mongod --shardsvr --replSet shardRepl --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard2:/data/db

  shard3:
    container_name: shard3
    image: mongo:4.2
    command: mongod --shardsvr --replSet shardRepl --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard3:/data/db

volumes:
  shard1: {}
  shard2: {}
  shard3: {}

