
version: '3'

services:

  mongo1:
    container_name: mongo1
    image: mongo:4.2
    command: mongod --configsvr --replSet clustermongo --port 27017 --dbpath /data/db
    ports:
      - 27017:27017
    volumes:
      - cfgsvr1:/data/db

  mongo2:
    container_name: mongo2
    image: mongo:4.2
    command: mongod --configsvr --replSet clustermongo --port 27017 --dbpath /data/db
    ports:
      - 27018:27017
    volumes:
      - cfgsvr2:/data/db

  mongo3:
    container_name: mongo3
    image: mongo:4.2
    command: mongod --configsvr --replSet clustermongo --port 27017 --dbpath /data/db
    ports:
      - 27019:27017
    volumes:
      - cfgsvr3:/data/db

volumes:
  mongo1: {}
  mongo2: {}
  mongo3: {}
